services:
  mssql:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    restart: always
    volumes:
      - volume:/var/lib/postgresql/data
volumes:
  volume:
