services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    env_file:
      - .env.local
    restart: always
    volumes:
      - volume:/var/opt/mssql
volumes:
  volume:
