services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env.local
    restart: no
    volumes:
      - volume:/data
volumes:
  volume:
